.\" (c) Copyright 2018 Richard W. Marinelli    Ver. 9.0.0
.\"
.\" This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
.\" "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
.\"
.\" Standard preamble:
.\" ========================================================================
.de Sh \" Subsection heading
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Bb \" Begin bullet item
.if t .sp .5v
.if n .sp
\fB*\fR
.in +.32i
.sp -1
..
.de Lb \" Begin list item
.if t .sp .5v
.if n .sp
\\$1
.in +.32i
.sp -1
..
.de Le \" End (bullet or) list item
.in
..
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.\" Set up some character translations and predefined strings.  \*(-- will
.\" give an unbreakable dash, \*(PI will give pi, \*(L" will give a left
.\" double quote, and \*(R" will give a right double quote.  \*(C+ will
.\" give a nicer C++.  Capital omega is used to do unbreakable dashes and
.\" therefore won't be available.  \*(C` and \*(C' expand to `' in nroff,
.\" nothing in troff, for use with C<>.
.tr \(*W-
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.ie n \{\
.    ds -- \(*W-
.    ds PI pi
.    if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.    if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\"  diablo 12 pitch
.    ds L" ""
.    ds R" ""
.    ds C` ""
.    ds C' ""
'br\}
.el\{\
.    ds -- \|\(em\|
.    ds PI \(*p
.    ds L" ``
.    ds R" ''
'br\}
.\"
.\" Escape single quotes in literal strings from groff's Unicode transform.
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\"
.\" Accent mark definitions (@(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2).
.\" Fear.  Run.  Save yourself.  No user-serviceable parts.
.    \" fudge factors for nroff and troff
.if n \{\
.    ds #H 0
.    ds #V .8m
.    ds #F .3m
.    ds #[ \f1
.    ds #] \fP
.\}
.if t \{\
.    ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.    ds #V .6m
.    ds #F 0
.    ds #[ \&
.    ds #] \&
.\}
.    \" simple accents for nroff and troff
.if n \{\
.    ds ' \&
.    ds ` \&
.    ds ^ \&
.    ds , \&
.    ds ~ ~
.    ds /
.\}
.if t \{\
.    ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.    ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.    ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.    ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.    ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.    ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.\}
.    \" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.    \" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.    \" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.    ds : e
.    ds 8 ss
.    ds o a
.    ds d- d\h'-1'\(ga
.    ds D- D\h'-1'\(hy
.    ds th \o'bp'
.    ds Th \o'LP'
.    ds ae ae
.    ds Ae AE
.\}
.rm #[ #] #H #V #F C
.\" ========================================================================
.\"
.TH MEMACS 1 "2018-01-13" "memacs 9.0" "MightEMacs Documentation"
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
memacs \- Fast and full-featured Emacs text editor
.SH "SYNOPSIS"
\&\fBmemacs\fR
.in +.7i
.sp -1v
{\fB\-?\fR, \fB\-usage\fR | \fB\-C\fR, \fB\-copyright\fR | \fB\-help\fR | \fB\-V\fR, \fB\-version\fR}
.in
.sp +0v
\&\fBmemacs\fR
.in +.7i
.sp -1v
[\fB\-d\fR, \fB\-dir\fR \fId\fR]
[\fB\-e\fR, \fB\-exec\fR \fIstmt\fR] [\fB\-G\fR, \fB\-global\-mode\fR [^]\fIm\fR[,...]]
[\fB\-i\fR, \fB\-inp\-delim\fR \fId\fR] [\fB\-N\fR, \fB\-no\-read\fR] [\fB\-n\fR, \fB\-no\-startup\fR]
[\fB\-o\fR, \fB\-otp\-delim\fR \fId\fR] [\fB\-path\fR \fIlist\fR] [\fB\-r\fR] [\fB\-S\fR, \fB\-shell\fR]
[[\fB@\fR]\fIfile\fR [{\fB+\fR|\fB\-\fR}}\fIline\fR] [\fB\-B\fR, \fB\-buf\-mode\fR [^]\fIm\fR[,...]] [\fB\-r\fR | \fB\-rw\fR]
[\fB\-s\fR, \fB\-search\fR \fIpat\fR] ...]
.SH "DESCRIPTION"
\&\fBmemacs\fR (or \fBmm\fR) is MightEMacs, a fast and full-featured Emacs text editor that uses a Text User Interface.
It is very robust, designed for the programmer, and focused on rapid text manipulation with few
keystrokes.  For speed and ease of learning, it uses a simplified scheme in which only four prefix keys
(\fIESC\fR, \fIC-x\fR, \fIC-c\fR, and \fIC-h\fR) are used and all commands are either one or two keystrokes.  Features include:
.in +.4i
.Bb
A user interface that provides for quick entry of numeric command prefixes and common commands,
and rigorous error detection and reporting.
.Le
.Bb
A comprehensive set of commands, including several for buffer, file, window, and screen management and control,
and a powerful group of text editing commands that allow deleting, killing, copying, or moving
words, partial or full lines, and fenced or marked regions of text either forward or backward with ease.
.Le
.Bb
Auto-indenting/outdenting (with hard tabs or space characters)
and fence matching for C, MightEMacs, Perl, Shell, and Ruby languages.
.Le
.Bb
Sophisticated search and replace features using plain text patterns or regular expressions with or without case sensitivity,
search and replace rings, and the ability to override the default search modes by specifying option characters on the pattern
itself.
.Le
.Bb
A simple but powerful scripting language that uses C-like operators and expressions and provides many features, including
numerous built-in variables and functions, statements for sophisticated looping and flow control, custom commands ("macros"),
macro nesting, recursion, and runaway loop detection.
User variables are either "global" (permanent) or "local" (exist only during
macro or buffer execution) and may be nil, Boolean, integer, string, or array data types.  The language also provides
the ability to code non-printable characters and imbedded expressions in string literals,
pause execution (to display a message), call a macro with arguments, assign values to macro arguments, and
call a macro or command as a function and return a value.
Built-in functions include \fIjoin\fR, which allows values of any type to be concatenated with a delimiter to form a string;
\fIsplit\fR, which splits a delimited string into an array;
\fIpush\fR, \fIpop\fR, \fIunshift\fR, and \fIshift\fR,
which allow values to be appended or prepended to, and subsequently
removed from an array; \fIquote\fR, \fIshQuote\fR, and \fItoString\fR,
which preserve or translate strings to visible form; \fIsub\fR, \fIsubstr\fR, and \fIsubline\fR,
which perform substitution and extraction operations on strings and buffer lines;
\fIbgets\fR, \fIbprint\fR, and \fIbprintf\fR, which read and write text from and to a buffer;
and \fIprompt\fR, which provides extensive user prompting and input
capabilities, including single-character entry and automatic completion of buffer names, variable names, and filenames.
.Le
.Bb
The ability to edit a file read from standard input, and the ability to
read or write files with CR, NL, or CR-LF line delimiters, including auto-detection on input.
.Le
.Bb
Simplified screen management and the ability to resize
MightEmacs's terminal dimensions when the size of the terminal emulator's window changes (for example, when using a
smart phone).
.Le
.Bb
Pop-up windows that can be scrolled backward or forward, and in half-pages or lines in addition to full pages
using a subset of commands from the "less" file viewer.
.Le
.Bb
Several "hooks" for customizing various operations (for example, reading and writing files or switching buffers)
including command hooks that allow for total control of the editing session from a macro.
.Le
.Bb
Quick informational displays; for example, \fIapropos\fR, \fIshowBuffers\fR, \fIshowCommands\fR, \fIshowKey\fR,
\fIshowKillRing\fR, \fIshowMacros\fR, \fIshowMarks\fR, \fIshowModes\fR, \fIshowScreens\fR, and \fIshowVariables\fR.
.Le
.Bb
Built-in help systems for both the beginner and advanced user.
.Le
.Bb
Several predefined macros for various tasks, including performing a search and replace on multiple files at once,
deleting and renaming files, formatting text,
language-specific "tools" such as finding a file containing a C function, and naming and saving keyboard macros in a
file so that they can be used in every editing session.
.Le
.PP
See on-line help (\fIESC ?\fR) for various help topics (including an introductory overview of the editor),
the \fIshowCommands\fR (\fIC-h c\fR) command for a list of all interactive commands and their key bindings, and the
\fIshowFunctions\fR (\fIC-h f\fR) and \fIshowVariables\fR (\fIC-h v\fR) commands for a list of all functions
(in addition to commands) and variables that are available for use in a script.
.SH "COMMAND SWITCHES AND ARGUMENTS"
.IP "\fB\-?\fR, \fB\-usage\fR" 4
Display usage and exit.
.IP "\fB\-C\fR, \fB\-copyright\fR" 4
Display copyright information and exit.
.IP "\fB\-d\fR, \fB\-dir\fR \fIdir\fR" 4
Specify a working directory to change to before reading files.
.IP "\fB\-e\fR, \fB\-exec\fR \fIstmt\fR" 4
Specify an expression statement to be executed.  Switch may be repeated.
.IP "\fB\-G\fR, \fB\-global\-mode\fR [^]\fIm\fR[,...]" 4
Specify one or more global modes to clear (^) or set (no ^), separated by commas.  Switch may be repeated.
.IP "\fB\-help\fR" 4
Display detailed help and exit.
.IP "\fB\-i\fR, \fB\-inp\-delim\fR \fId\fR" 4
Specify one or two characters (processed as a double-quoted "..." string) to use as file input record delimiter(s); otherwise,
the first NL, CR-LF, or CR found when a file is read is used.  Non-printable characters are specified in \fI\\x\fR
form, or as \fI\\0n\fR (octal) or \fI\\xn\fR (hexadecimal) values; for example, \'\fI\\r\fR\' for CR or
\'\fI\\015\\012\fR\' for CR-LF.
.IP "\fB\-N\fR, \fB\-no\-read\fR" 4
Do not read first file at startup.
.IP "\fB\-n\fR, \fB\-no\-startup" 4
Do not load the site or user startup file.
.IP "\fB\-o\fR, \fB\-otp\-delim\fR \fId\fR" 4
Specify one or two characters (processed as a double-quoted "..." string) to use as file output record delimiter(s); otherwise,
delimiter(s) found in input file ($BufInpDelim) is used.
.IP "\fB\-path\fR \fIlist\fR" 4
Specify colon-separated list of script search directories to prepend to existing path.
.IP "\fB\-r\fR" 4
Read-only: open all files with RdOnly buffer mode \fIon\fR by default; otherwise, \fIoff\fR.
.IP "\fB\-S\fR, \fB\-shell\fR" 4
Execute file as a MightEMacs "shell script".  First line of file must contain "#!" followed by the pathname to the
MightEMacs binary and the \fB\-S\fR or \fB\-shell\fR switch; for example, "#!/usr/local/bin/memacs -S".  Other switches may be
specified as well.  The file must be executed as a shell script (with execute permission).  Any arguments specified on
the command line following the last switch will be passed to the MightEMacs script coded in the file.  Additionally, an
\fIexit\fR command must be coded in the script to terminate MightEMacs after the script completes (if desired) to prevent
MightEMacs from entering interactive mode.
.IP "\fB\-V\fR, \fB\-version\fR" 4
Display program version and exit.
.IP "\fB@\fR\fIfile\fR" 4
Execute specified script file (in path) before processing argument(s) that follow it.  Multiple script files may be specified
intermixed with data files.
.IP "\fIfile\fR" 4
File to open for viewing or editing.  If "\-" is specified as the filename, data is read from standard input into buffer
"untitled".  Multiple data files may be specified intermixed with script files.
.SH "ARGUMENT SWITCHES"
.IP "{\fB+\fR|\fB\-\fR}\fIline\fR" 4
Go to specified line number from beginning (+) or end (-) of data file, or to end of file if line number is zero.
.IP "\fB\-B\fR, \fB\-buf\-mode\fR [^]\fIm\fR[,...]" 4
Specify one or more buffer modes to clear (^) or set (no ^) on data file, separated by commas.  Switch may be repeated.
.IP "\fB\-r\fR" 4
Read-only: open data file with RdOnly buffer mode \fIon\fR.
.IP "\fB\-rw\fR" 4
Read-write: open data file with RdOnly buffer mode \fIoff\fR (overrides command-level \fB\-r\fR switch).
.IP "\fB\-s\fR, \fB\-search\fR \fIpat\fR" 4
Search for specified pattern in data file.
.SH "ENVIRONMENT"
.\" .IP "\fB\s-1MMPATH\s0\fR" 4
.IP "\fBMMPATH\fR" 4
The script execution path is initially set to the value of this environmental variable if it is defined,
even if it is null.
.SH "NOTES"
.Bb
If the \fB\-no\-read\fR switch is not specified, one data file is read after all switches and arguments are processed,
determined as follows: if the \fB+\fR or \fB-\fR (go to line) or \fB-search\fR switch is specified on a data file argument,
the corresponding file is read and the action is performed; otherwise, the first data file specified is read.
.Le
.Bb
The \fB\-r\fR and \fB\-rw\fR argument switches may not both be specified.
.Le
.Bb
MightEMacs takes the following steps at startup to initialize its environment and prepare to enter interactive mode:
.Sp
.in +.4i
.Lb 1.
Buffer "untitled" is created and set as the current buffer.
.Le
.Lb 2.
The script execution path is initialized to ":/usr/local/lib/memacs" (or ":/usr/lib/memacs" on a Debian system)
or to the value of the MMPATH environmental variable if it is defined.
.Le
.Lb 3.
If the \fB-no-startup\fR switch was not specified,
the site startup file \fImemacs.mm\fR is searched for on the execution path and executed if found.
.Le
.Lb 4.
If the \fB-no-startup\fR switch was not specified and the HOME environmental variable is defined,
the user startup file ".memacs" is searched for in the HOME directory (only), and executed if found.
.Le
.Lb 5.
The "createBuf" hook is executed if it is defined.
.Le
.Lb 6.
The "chDir" hook is executed if it is defined.
.Le
.Lb 7.
Switches and arguments on the command line (if any) are processed in order until no arguments remain (or just
until all switches have been processed if the \fB-shell\fR switch was specified).
.Sp
If any \fB@\fR\fIfile\fR argument is found,
the indicated file is searched for verbatim if the name contains a \fI/\fR; otherwise, it is searched for in
the directories in the current execution path (which may have been changed by a prior \fB-path\fR or \fB-exec\fR switch).
In either case, the file with \fI.mm\fR appended is also searched for unless that extension is already present in
\fIfile\fR.
If the file is found, it is executed; otherwise, execution halts with a non-zero return code and error message.
Execution will also halt if a fatal error occurs or the editor is instructed to exit during execution
of a \fB-exec\fR switch or a script.
.Sp
If a \fB-S\fR or \fB-shell\fR switch is found, the argument that follows the last switch
it is assumed to be an absolute file pathname and is executed verbatim as a script.
Any arguments following the pathname argument are passed to the script as arguments.
.Le
.Lb 8.
If no exit was warranted from the previous step, the \fB-no-read\fR switch was not specified, and one or more files were
specified to edit, the file associated with a \fB+\fR, \fB-\fR, or \fB-search\fR argument switch (or first file
otherwise) is read into a new buffer in the current window and buffer "untitled" is deleted.
.Le
.Lb 9.
Lastly, if a \fB+\fR, \fB-\fR, or \fB-search\fR switch was specified, it is executed in the current buffer.
The contents of the current window are then displayed and the user may begin entering commands.
.Le
.in -.8i
.Bb
In order for messages and prompts to be viewed without truncation or in condensed form on the message line,
it is recommended that the terminal width be at least 96 columns.
.Le
.SH "FILES"
.IP "\fI\s-1/usr/local/bin/memacs\s0\fR" 4
The MightEMacs executable.
.IP "\fI\s-1/usr/local/bin/mm\s0\fR" 4
Alternate MightEMacs executable.
.IP "\fI\s-1/usr/local/lib/memacs/memacs.mm\s0\fR" 4
.sp -1v
.IP "\fI\s-1/usr/local/lib/memacs/site.mm\s0\fR" 4
Standard and user-customizable site startup files.
.IP "\fI\s-1~/.memacs\s0\fR" 4
User startup file.
.IP "\fI\s-1/usr/local/lib/memacs/cToolbox.mm\s0\fR" 4
.sp -1v
.IP "\fI\s-1/usr/local/lib/memacs/memacsToolbox.mm\s0\fR" 4
.sp -1v
.IP "\fI\s-1/usr/local/lib/memacs/rubyToolbox.mm\s0\fR" 4
.sp -1v
.IP "\fI\s-1/usr/local/lib/memacs/toolbox.mm\s0\fR" 4
Files containing macros (tools) for editing C, MightEMacs, and Ruby source files and scripts.
Loaded automatically when a file with a \fI.c\fR or \fI.h\fR, \fI.mm\fR, or \fI.rb\fR extension
is opened for editing (via the \fIinitLang\fR macro in \fImemacs.mm\fR).
.IP "\fI\s-1/usr/local/lib/memacs/blockFormat.mm\s0\fR" 4
File containing macros for formatting line "blocks", which may be comments or numbered list items.
.IP "\fI\s-1/usr/local/lib/memacs/keyMacro.mm\s0\fR" 4
File containing macros for naming, saving, and retrieving keyboard macros across editing sessions.
.IP "\fI\s-1/usr/local/lib/memacs/help/*\s0\fR" 4
Files used by built-in help system which is entered via help command (\fIESC ?\fR).
.PP
Note: The files listed above are located in /usr instead of /usr/local on Debian systems.
.SH "BUGS"
Due to the nature of how MightEMacs manages text, all lines are assumed to implicitly end with a line delimiter, including
the last line in a buffer.  Consequently, the last character written from a non-empty buffer to a file will always be a
line delimiter (usually a newline character) even if the file did not contain one when it was read.  This may be fixed in
a future version.
.Sp
To report bugs in the editor, please contact the author.  Bug reports should include a detailed description
along with information to reproduce.
.SH "AUTHOR"
MightEMacs is maintained by Richard W. Marinelli <italian389@yahoo.com>.  It was originally based on the MicroEMACS 3.12
text editor written by Daniel M. Lawrence, et al. in 1993, but it has been extensively rewritten and enhanced, runs on
Unix platforms exclusively, and little or none of the original code remains.  See the \fIabout\fR command
(\fIC-h A\fR) for version, copyright, contact, licensing, and build information.
