// (c) Copyright 2016 Richard W. Marinelli
//
// This work is licensed under the GNU General Public License (GPLv3).  To view a copy of this license, see the
// "License.txt" file included with this distribution or visit http://www.gnu.org/licenses/gpl-3.0.en.html.
//
// efunc.h	External function prototype declarations for MightEMacs.

// Functions called from multiple source files in alphabetical order.
extern int abortinp(void);
extern int abortOp(Value *rp,int n);
extern int aboutMM(Value *rp,int n);
extern int adjustmode(Value *rp,int n,int type,Value *valp);
extern int afind(char *anamep,int op,CFABPtr *cfab,Alias **app);
extern int aliasCFM(Value *rp,int n);
extern int allowedit(bool edit);
extern int amfind(char *namep,int op,uint type);
extern int apropos(Value *mstrp,char *prmtp);
#if 0
extern int asc_int(char *srcp,int *resultp,bool query);
#endif
extern int asc_long(char *srcp,long *resultp,bool query);
extern int backch(int n);
extern int backChar(Value *rp,int n);
extern int backLine(Value *rp,int n);
extern int backln(int n);
extern int backPage(Value *rp,int n);
extern int backWord(Value *rp,int n);
extern int bactivate(Buffer *bufp);
extern int bappend(Buffer *bufp,char *text);
extern int bclear(Buffer *bufp,uint flags,bool *clearedp);
extern int bcomplete(Value *rp,char *prmtp,char *defname,uint op,Buffer **bufpp,bool *createdp);
extern Buffer *bdefault(bool backward,bool active);
extern int bdelete(Buffer *bufp,uint flags);
extern int beeper(Value *rp,int n);
extern int beginKeyMacro(Value *rp,int n);
extern int beginText(Value *rp,int n);
extern int begintxt(void);
extern int beline(Value *rp,int n,bool end);
extern int bfind(char *name,uint cflags,uint bflags,Buffer **bufpp,bool *createdp);
extern int bftab(int n);
extern void bftowf(Buffer *bufp,EWindow *winp);
extern int binary(char *keyp,char *(*tval)(int i),int tsize);
extern int bindKeyCM(Value *rp,int n);
extern int boundary(Dot *dotp,int dir);
extern int bpop(Buffer *bufp,bool altmodeline,bool endprompt);
extern int bscratch(char *rp,Buffer **bufpp);
extern Buffer *bsrch(char *bname,Buffer **bufpp);
extern int bswitch(Buffer *bufp);
extern int bufcount(void);
extern long buflength(Buffer *bufp,long *lp);
extern int bufop(Value *rp,int n,char *prmtp,uint op,uint flag);
extern int bumpvar(ENode *np,bool incr,bool pre);
extern int caseline(int n,char *trantab);
extern int caseregion(int n,char *trantab);
extern int cfabsearch(char *strp,CFABPtr *cfabp,uint selector);
extern int changedir(Value *rp,int n);
extern int chcase(int ch);
extern int chgtext(Value *rp,int n,Buffer *bufp,uint t,CmdFunc *cfp);
#if COLOR
extern int chkcpy(char **destp,char *srcp,size_t destlen,char *emsgp);
#endif
extern int chkopts(char *patp,ushort *flagp);
extern int clearBuf(Value *rp,int n);
extern void clearKeyMacro(bool stop);
extern void clfname(Buffer *bufp);
extern int copyreg(Region *regp);
#if WORDCOUNT
extern int countWords(Value *rp,int n);
#endif
extern void cpause(int n);
extern int ctoec(int c);
extern int cycle_ring(int n,bool msg);
extern char *defnil(char *strp);
extern int deleteAlias(Value *rp,int n);
extern int deleteAM(char *prmtp,uint selector,char *emsg);
extern int deleteBlankLines(Value *rp,int n);
extern int deleteBuf(Value *rp,int n);
extern int deleteMacro(Value *rp,int n);
extern int deleteMark(Value *rp,int n);
extern int deleteScreen(Value *rp,int n);
extern int deleteTab(Value *rp,int n);
extern int deleteWind(Value *rp,int n);
extern int delwhite(int n);
extern int derefn(Value *valp,char *namep);
extern int derefv(Value *valp,VDesc *vdp);
extern int detabLine(Value *rp,int n);
extern int dkregion(int n,bool kill);
extern int dobuf(Value *rp,int n,Buffer *bufp,char *runpath,uint flags);
extern int doestmt(Value *rp,char *clp,int termch,char **clpp);
extern int dofile(Value *rp,char *fname,int n,uint flags);
#if MMDEBUG & DEBUG_SCRDUMP
extern void dumpscreens(char *msg);
#endif
#if MMDEBUG & DEBUG_VALUE
void dumpvars(void);
#endif
extern char *dupchr(char *s,int c,int len);
extern int dupLine(Value *rp,int n);
extern int ektoc(uint ek);
extern char *ektos(uint ek,char *destp);
extern int endKeyMacro(Value *rp,int n);
extern int endWord(Value *rp,int n);
extern int entabLine(Value *rp,int n);
extern int eopendir(char *fspec,char **fpp);
extern int ereaddir(void);
extern int ernd(void);
extern int eval(Value *rp,int n);
extern int evalslit(Value *rp,char *srcp);
extern bool exactbmode(void);
extern int exechook(Value *rp,int n,HookRec *hrp,uint arginfo,...);
extern bool extrasym(void);
extern void faceinit(WindFace *wfp,Line *lnp,Buffer *bufp);
extern char *fbasename(char *name,bool withext);
extern char *fdirname(char *name,int n);
extern int feval(Value *rp,int n,CmdFunc *cfp);
extern int fexist(char *fn);
extern int ffclose(bool otpfile);
extern int ffgetline(uint *lenp);
extern CmdFunc *ffind(char *cnamep);
extern int ffputline(char *buf,int buflen);
extern int ffropen(char *fn,bool required);
extern int ffwopen(char *fn,int mode);
extern int fileout(Value *rp,char *prmtp,int mode);
extern char *fixnull(char *s);
extern int fmatch(int ch);
extern int forwch(int n);
extern int forwChar(Value *rp,int n);
extern int forwLine(Value *rp,int n);
extern int forwln(int n);
extern int forwPage(Value *rp,int n);
extern int forwWord(Value *rp,int n);
extern void freerpat(Match *mtp);
extern void freespat(Match *mtp);
extern int funcarg(Value *rp,uint aflags);
extern int ge_comma(ENode *np);
extern int getarg(Value *rp,char *prmtp,char *defvalp,uint terminator,uint maxlen,uint aflags);
extern KeyDesc *getbind(uint ek);
extern int getbuflist(Value *rp);
extern int getccol(void);
extern int getcfam(char *prmtp,uint selector,CFABPtr *cfabp,char *emsg0,char *emsg1);
extern int getcfm(char *prmtp,CFABPtr *cfabp,uint selector);
extern bool getcomma(bool required);
extern int getfile(Value *rp,int n,bool view);
extern enum e_sym getident(char **srcpp,ushort *lenp);
extern int getkey(uint *keyp);
extern char *getkname(KeyDesc *kdp);
extern int getkseq(uint *keyp,KeyDesc **kdpp);
extern long getlinenum(Buffer *bufp,Line *targlnp);
extern bool getnum(char *prmtp,int *np);
extern int getpath(Value *pathp,char *fname);
extern KeyDesc *getpentry(CFABPtr *cfabp);
extern int getregion(Region *regp,bool *allp);
extern int getsym(void);
extern int gettermsize(ushort *colp,ushort *rowp);
extern int getwid(ushort *widp);
extern int getwindlist(Value *rp);
extern int getwkdir(char **strpp,bool force);
extern int getwpos(EWindow *winp);
extern int gotoLine(Value *rp,int n);
extern int gotoMark(Value *rp,int n);
extern int growKeyMacro(void);
extern void grpclear(Match *mtp);
extern int gswind(Value *rp,int n,bool grow);
extern int gtfilename(Value *rp,char *prmtp,uint flags);
extern bool havesym(enum e_sym sym,bool required);
extern bool havewhite(void);
extern int help(Value *rp,int n);
extern int huntBack(Value *rp,int n);
extern int huntForw(Value *rp,int n);
extern int ifile(char *fname,int n);
extern int indentRegion(Value *rp,int n);
extern void initchars(void);
extern int insertBuf(Value *rp,int n);
extern int insertFile(Value *rp,int n);
extern int insertLineI(Value *rp,int n);
extern int insertPipe(Value *rp,int n);
extern int inserti(Value *rp,int n);
extern int insnlspace(Value *rp,int n,bool nl);
extern int inspre(int c);
extern int insrfence(int c);
extern int instab(int n);
#if 0
extern char *int_asc(int n,char *destp);
#endif
extern bool intval(Value *vp);
extern bool intvar(VDesc *vdp);
extern bool inwind(EWindow *winp,Line *lnp);
extern bool inword(void);
extern int iortext(Value *vp,int n,uint t,bool kill);
extern bool is_lower(int ch);
extern bool is_upper(int ch);
extern bool is_white(Line *lnp,int length);
extern bool isident1(int c);
extern bool isletter(int ch);
extern bool isnil(char *strp);
extern int join(Value *rp,Value *delimp,int reqct,uint flags);
extern int joinLines(Value *rp,int n);
extern int joinWind(Value *rp,int n);
extern void kcycle(void);
extern int kdcbword(int n,int kdc);
extern bool kdcfencedreg(int kdc);
extern int kdcfword(int n,int kdc);
extern int kdcline(int n,int kdc);
extern int kdctext(int n,int kdc,Region *regp);
extern void kdelete(Kill *kp);
extern int kinsert(Kill *kp,int direc,int c);
extern void kprep(bool kill);
extern int lalloc(int used,Line **lnpp);
extern void lchange(Buffer *bufp,uint flags);
extern int ldelete(long n,uint flags);
extern void lfree(Line *lnp);
extern int linsert(int n,int c);
extern int linstr(char *s);
extern int lnewline(void);
extern int loadbind(void);
extern char *long_asc(long n,char *destp);
extern int lookup_color(char *strp);
extern int lcWord(Value *rp,int n);
extern int ltos(Value *destp,int val);
extern int markBuf(Value *rp,int n);
extern void mcclear(Match *mtp);
extern int mccompile(Match *mtp);
extern int mcscan(int n,int direct);
extern int mfind(ushort id,Mark **mkpp,uint flags);
extern void mkdeltas(void);
extern char *mklower(char *destp,char *srcp);
extern char *mkpat(char *destp,Match *mtp);
extern char *mkupper(char *destp,char *srcp);
extern int mlerase(uint flags);
extern int mlprintf(uint flags,char *fmt,...);
extern int mlputc(uint flags,int c);
extern int mlputs(uint flags,char *s);
extern int mlputv(uint flags,Value *vp);
extern int mlrestore(void);
extern int mlyesno(char *prmtp,bool *resultp);
extern void mnuke(Buffer *bufp,bool force);
extern int moveWindUp(Value *rp,int n);
extern int movecursor(int row,int col);
extern void mset(Mark *mkp,EWindow *winp);
extern int narrowBuf(Value *rp,int n);
extern int newcol(int c,int col);
extern int newlineI(Value *rp,int n);
extern int newrpat(char *patp,Match *mtp);
extern int newScreen(Value *rp,int n);
extern int newspat(char *patp,Match *mtp,ushort *flagsp);
extern KeyDesc *nextbind(KeyWalk *kwp);
extern int nextScreen(Value *rp,int n);
extern int nextWind(Value *rp,int n);
extern char *nilcpy(char *destp);
extern void nodeinit(ENode *np,Value *rp);
extern char *nonwhite(char *s);
extern int notice(Value *rp,int n);
extern int onlyWind(Value *rp,int n);
extern int openLine(Value *rp,int n);
extern int otherfence(Region *regp);
extern int outdentRegion(Value *rp,int n);
extern int overprep(int n);
extern char *pad(char *s,int len);
extern int parsebegin(Parse *newp,char *clp,int termch);
extern void parseend(Parse *oldp);
extern int parsetok(Value *destp,char **srcpp,int delim);
extern int pathsearch(char **rpp,char *namep,bool hflag);
extern int pipeBuf(Value *rp,int n);
extern bool plainsearch(void);
extern int pnbuffer(Value *rp,int n,bool prev);
extern void ppfree(Buffer *bufp);
extern int prevWind(Value *rp,int n);
extern int putline(int row,int col,char *buf);
extern int quit(Value *rp,int n);
extern int quote(StrList *destp,char *srcp,bool full);
extern int quoteChar(Value *rp,int n);
extern int rcclear(void);
extern int rcsave(void);
extern int rcset(int status,uint flags,char *fmt,...);
extern int rdfile(Value *rp,int n,char *fname,bool scratch);
extern int readBuf(Value *rp,int n);
extern int readPipe(Value *rp,int n);
extern int readin(Buffer *bufp,char *fname,bool keep);
extern int readpattern(char *prmtp,bool srchpat);
extern bool rebmode(void);
extern int recmp(Value *sp,int scanoff,Match *mtp,int *resultp);
extern char *regcpy(char *buf,Region *regp);
extern int reglines(int *np,bool *allp);
#if 0
extern int regvcpy(Value *destp,Region *regp);
#endif
extern int render(Value *rp,int n,Buffer *bufp,uint flags);
extern int replstr(Value *rp,int n);
extern int resetTermc(Value *rp,int n);
extern int resizeWind(Value *rp,int n);
extern int restorecursor(void);
extern int rmccompile(Match *mtp);
extern int rparsetok(Value *destp,char **srcpp,char *basep,int delim);
extern int run(Value *rp,int n);
extern int savebufs(int n,bool showcount);
extern void savecursor(void);
extern int savematch(Match *mtp);
extern int scan(int n,int direct);
extern int scratchBuf(Value *rp,int n);
extern int scrcount(void);
extern int searchBack(Value *rp,int n);
extern int searchForw(Value *rp,int n);
extern int selectBuf(Value *rp,int n);
extern int setBufFile(Value *rp,int n);
extern int setBufName(Value *rp,int n);
extern int setMark(Value *rp,int n);
extern int setccol(int pos);
extern int setfname(Buffer *bufp,char *fname);
extern int setHook(Value *rp,int n);
extern int seti(Value *rp,int n);
extern int setpath(char *path,bool prepend);
extern int settab(int size,bool hard);
extern void settermsize(ushort ncol,ushort nrow);
extern int setvar(Value *rp,int n);
extern int setwlist(char *wclistp);
extern int sfind(ushort scr_num,Buffer *bufp,EScreen **spp);
extern int shellCLI(Value *rp,int n);
extern int shellCmd(Value *rp,int n);
extern int showBindings(Value *rp,int n);
extern int showBuffers(Value *rp,int n);
extern int showFunctions(Value *rp,int n);
extern int showHooks(Value *rp,int n);
extern int showKey(Value *rp,int n);
extern int showKillRing(Value *rp,int n);
extern int showMarks(Value *rp,int n);
#if MMDEBUG & DEBUG_SHOWRE
extern int showRegexp(Value *rp,int n);
#endif
extern int showScreens(Value *rp,int n);
extern int showVariables(Value *rp,int n);
#if COLOR
extern int spal(char *pstr);
#endif
extern int spanwhite(bool end);
extern int splitWind(Value *rp,int n);
extern int sswitch(EScreen *scrp);
extern int stoek(char *keylitp,int *resultp);
extern int strexpand(StrList *slp,char *estrp);
extern int strfmt(Value *rp,int n,Value *formatp,Value *arg1p);
extern char *stripstr(char *srcp,int op);
extern char *strrev(char *s);
extern char *strsamp(char *srcp,size_t srclen,size_t maxlen);
extern int strsub(Value *rp,int n,Value *sp,char *sstrp,char *rstrp,ushort flags);
extern bool strval(Value *vp);
extern int suspendEMacs(Value *rp,int n);
extern int swapMark(Value *rp,int n);
extern int swapmid(ushort id);
extern int sysbuf(char *rootp,Buffer **bufpp);
extern int tabstop(int n);
extern int terminp(Value *rp,char *prmtp,char *defvalp,uint terminator,uint maxlen,uint aflags);
extern char *timeset(void);
extern int tcWord(Value *rp,int n);
extern int toint(Value *vp);
extern int tostr(Value *vp,uint flags);
extern int traverseLine(Value *rp,int n);
extern int trimLine(Value *rp,int n);
extern void tungetc(uint ek);
extern int typahead(int *countp);
extern int unbindKey(Value *rp,int n);
extern void unbindent(KeyDesc *kdp);
extern int update(bool force);
extern void uphard(void);
extern void upmode(Buffer *bufp);
extern int ucWord(Value *rp,int n);
extern UVar *uvarfind(char *namep);
extern uint varct(uint flags);
extern void varlist(char *vlistv[],uint count,uint flags);
extern bool vistfn(Value *vp,int tfn);
extern bool vistrue(Value *vp);
extern char *vizstr(Value *vp,bool *wasStr);
extern int vnilmm(Value *vp);
extern int vrcset(void);
extern int vtinit(void);
extern int vttidy(bool force);
extern bool vvoid(Value *vp);
extern void wftobf(EWindow *winp,Buffer *bufp);
extern int whence(Value *rp,int n);
#if 0
extern char *white(char *s);
#endif
extern int widenBuf(Value *rp,int n);
extern int wincount(void);
extern EWindow *wnextis(EWindow *winp);
extern int wrapLine(Value *rp,int n);
extern int wrapWord(Value *rp,int n);
extern int writeBuf(Value *rp,int n);
extern int writeout(Buffer *bufp,char *fn,int mode);
extern int wscroll(Value *rp,int n,int (*winfunc)(Value *rp,int n),int (*pagefunc)(Value *rp,int n));
extern void wswitch(EWindow *winp);
extern void wupd_modeline(EWindow *winp,Buffer *popbuf);
extern bool wupd_newtop(EWindow *winp,Line *lnp,int n);
extern int xeqBuf(Value *rp,int n);
extern int xeqFile(Value *rp,int n);
extern int xeqKeyMacro(Value *rp,int n);
extern int yankPop(Value *rp,int n);
